<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
  <atom:link href="<?php echo BASE_URL; ?><?php echo ($ns ? $ns . '/rss' :
                                                           ($query ? '?q=' . $query . '&amp;rss' : 'rss')); ?>" rel="self" type="application/rss+xml"></atom:link>
  <title>KVAZAR - <?php echo ($namespaceValue ? $namespaceValue :
                                               ($namespaceHash ? $namespaceHash :
                                                                ($query ? 'SEARCH - ' . $query : false))); ?></title>
  <description>Observe Kevacoin Universe</description>
  <link><?php echo BASE_URL; ?><?php echo ($ns ? $ns : ($query ? '?q=' . $query : false)); ?></link>
  <?php foreach ($data as $item) { ?>
  <item>
    <title><?php echo $item['key']; ?></title>
    <guid><?php echo BASE_URL; ?><?php echo $item['txid']; ?></guid>
    <pubDate><?php echo $item['time']; ?></pubDate>
    <description><?php echo $item['value']; ?></description>
    <link><?php echo BASE_URL; ?><?php echo $item['txid']; ?></link>
  </item>
  <?php } ?>
</channel>
</rss>